import type { YieldProtocol } from './types';

export const PROTOCOL_SEED: YieldProtocol[] = [
  {
    id: "bitcoin-staking",
    name: "Bitcoin Staking (Native BTC)",
    shortName: "Bitcoin Staking",
    slug: "bitcoin-staking",
    description: "Self-custodial native BTC yield — your Bitcoin stays on L1 under your own keys. Phase 1 of the Stacks 2026 roadmap.",
    category: "Staking",
    icon: "₿",
    websiteUrl: "https://www.stacks.co/yield",
    appUrl: "https://www.stacks.co/yield",
    apy: 3.0, apyBase: 3.0, apyReward: 0,
    apyRange: { min: 3, max: 5 },
    earnAsset: "BTC",
    tvlUsd: 0,
    tvl7dChange: 0, tvl30dChange: 0,
    riskScore: 2.0, healthScore: 9.0, opportunityScore: 0,
    ilRisk: "None", smartContractRisk: "Very Low",
    audited: false, auditFirms: [],
    protocolAge: 0,
    strategy: "Bond BTC (kept self-custodial on Bitcoin L1) paired with a ≥5% STX ratio to earn native BTC yield from a waterfall of miner revenue. Rewards paid in BTC.",
    lockupPeriod: "Cycle-based bond",
    minimumDeposit: null,
    supportedAssets: ["BTC", "sBTC", "STX"],
    lastUpdated: new Date().toISOString(),
    status: "coming-soon",
    launchTarget: "Q3 2026",
    capacityNote: "3,000 BTC initial capacity · target 3% BTC APY · 5% min STX pairing",
  },
  {
    id: "dual-stacking",
    name: "Dual Stacking",
    shortName: "Dual Stacking",
    slug: "dual-stacking",
    description: "Stack STX and hold sBTC simultaneously for boosted BTC yield",
    category: "Staking",
    icon: "🔗",
    websiteUrl: "https://stacks.co",
    appUrl: "https://app.stacks.co",
    apy: 10.0, apyBase: 10.0, apyReward: 0,
    apyRange: { min: 7, max: 10 },
    earnAsset: "BTC",
    tvlUsd: 100_000_000,
    tvl7dChange: 3.2, tvl30dChange: 12.4,
    riskScore: 2.2, healthScore: 9.2, opportunityScore: 8.8,
    ilRisk: "None", smartContractRisk: "Very Low",
    audited: true, auditFirms: ["Clarity Alliance"],
    protocolAge: 6,
    strategy: "Stack STX + hold sBTC for BTC-denominated yield via Proof of Transfer",
    lockupPeriod: "Cycle-based (~2 weeks)",
    minimumDeposit: null,
    supportedAssets: ["STX", "sBTC"],
    defiLlamaProject: "stacks",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "native-stacking",
    name: "Native STX Stacking",
    shortName: "STX Stacking",
    slug: "native-stacking",
    description: "Lock STX in Proof of Transfer consensus to earn BTC rewards",
    category: "Staking",
    icon: "⚡",
    websiteUrl: "https://stacks.co",
    appUrl: "https://app.stacks.co",
    apy: 9.2, apyBase: 9.2, apyReward: 0,
    apyRange: { min: 7, max: 11 },
    earnAsset: "BTC",
    tvlUsd: 200_000_000,
    tvl7dChange: 1.1, tvl30dChange: 5.2,
    riskScore: 1.8, healthScore: 9.5, opportunityScore: 7.2,
    ilRisk: "None", smartContractRisk: "Very Low",
    audited: true, auditFirms: ["Multiple"],
    protocolAge: 36,
    strategy: "Lock STX in PoX consensus. Bitcoin miners transfer BTC to stackers each cycle.",
    lockupPeriod: "Cycle-based (~2 weeks)",
    minimumDeposit: 100,
    supportedAssets: ["STX"],
    defiLlamaProject: "stacks",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "hermetica-hbtc",
    name: "Hermetica — hBTC Vault",
    shortName: "Hermetica",
    slug: "hermetica-hbtc",
    description: "Delta-neutral BTC yield via funding rate arbitrage strategy",
    category: "Yield",
    icon: "⚗️",
    websiteUrl: "https://hermetica.fi",
    appUrl: "https://app.hermetica.fi",
    apy: 12.5, apyBase: 3.5, apyReward: 9.0,
    apyRange: { min: 8, max: 16 },
    earnAsset: "BTC",
    tvlUsd: 45_000_000,
    tvl7dChange: 4.1, tvl30dChange: 18.3,
    riskScore: 5.8, healthScore: 7.6, opportunityScore: 8.4,
    ilRisk: "None", smartContractRisk: "Medium",
    audited: true, auditFirms: ["Clarity Alliance"],
    protocolAge: 18,
    strategy: "BTC→sBTC→Zest collateral→borrow USDCx→convert USDh→earn funding rates",
    lockupPeriod: "None",
    minimumDeposit: null,
    supportedAssets: ["BTC", "sBTC"],
    defiLlamaProject: "hermetica",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "stackingdao-ststx",
    name: "StackingDAO — stSTX",
    shortName: "StackingDAO",
    slug: "stackingdao-ststx",
    description: "Liquid stacking — earn BTC yield while keeping STX liquid",
    category: "Staking",
    icon: "🏛️",
    websiteUrl: "https://stackingdao.com",
    appUrl: "https://app.stackingdao.com",
    apy: 8.7, apyBase: 8.7, apyReward: 0,
    apyRange: { min: 7, max: 10 },
    earnAsset: "BTC",
    tvlUsd: 20_000_000,
    tvl7dChange: 0.8, tvl30dChange: 3.1,
    riskScore: 3.1, healthScore: 8.4, opportunityScore: 7.9,
    ilRisk: "None", smartContractRisk: "Low",
    audited: true, auditFirms: ["Clarity Alliance"],
    protocolAge: 24,
    strategy: "Deposit STX → receive stSTX (rebasing token). stSTX accrues BTC yield.",
    lockupPeriod: "None (liquid)",
    minimumDeposit: null,
    supportedAssets: ["STX"],
    defiLlamaProject: "stackingdao",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "zest-btc-supply",
    name: "Zest — BTC Supply",
    shortName: "Zest",
    slug: "zest-btc-supply",
    description: "Supply Bitcoin to earn lending interest from BTC borrowers",
    category: "Lending",
    icon: "🍊",
    websiteUrl: "https://zestprotocol.com",
    appUrl: "https://app.zestprotocol.com",
    apy: 3.5, apyBase: 3.5, apyReward: 0,
    apyRange: { min: 2, max: 5 },
    earnAsset: "BTC",
    tvlUsd: 75_900_000,
    tvl7dChange: 2.2, tvl30dChange: 9.8,
    riskScore: 3.5, healthScore: 9.1, opportunityScore: 5.2,
    ilRisk: "None", smartContractRisk: "Low",
    audited: true, auditFirms: ["Clarity Alliance"],
    protocolAge: 20,
    strategy: "Supply BTC to lending pool. Borrowers pay interest. Withdraw anytime.",
    lockupPeriod: "None",
    minimumDeposit: null,
    supportedAssets: ["BTC", "sBTC"],
    defiLlamaProject: "zest-protocol",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "granite-btc-supply",
    name: "Granite — BTC Supply",
    shortName: "Granite",
    slug: "granite-btc-supply",
    description: "Supply BTC to institutional-grade lending protocol",
    category: "Lending",
    icon: "🪨",
    websiteUrl: "https://granite.fi",
    appUrl: "https://app.granite.fi",
    apy: 4.8, apyBase: 4.8, apyReward: 0,
    apyRange: { min: 3, max: 6 },
    earnAsset: "BTC",
    tvlUsd: 26_000_000,
    tvl7dChange: 1.5, tvl30dChange: 7.2,
    riskScore: 4.0, healthScore: 8.2, opportunityScore: 5.8,
    ilRisk: "None", smartContractRisk: "Low",
    audited: true, auditFirms: ["Clarity Alliance"],
    protocolAge: 12,
    strategy: "Supply BTC to institutional borrowers. Higher rates than Zest.",
    lockupPeriod: "None",
    minimumDeposit: null,
    supportedAssets: ["BTC", "sBTC"],
    defiLlamaProject: "granite-protocol",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "bitflow-sbtc-stx",
    name: "Bitflow — sBTC-STX",
    shortName: "Bitflow",
    slug: "bitflow-sbtc-stx",
    description: "LP in sBTC-STX pool via Bitflow's HODLMM",
    category: "DEX/LP",
    icon: "🌊",
    websiteUrl: "https://bitflow.finance",
    appUrl: "https://app.bitflow.finance",
    apy: 14.2, apyBase: 6.0, apyReward: 8.2,
    apyRange: { min: 8, max: 22 },
    earnAsset: "sBTC + STX",
    tvlUsd: 5_000_000,
    tvl7dChange: 3.5, tvl30dChange: 14.0,
    riskScore: 5.5, healthScore: 6.8, opportunityScore: 7.8,
    ilRisk: "Low", smartContractRisk: "Medium",
    audited: true, auditFirms: ["Clarity Alliance"],
    protocolAge: 15,
    strategy: "Provide liquidity to sBTC-STX pair. Earn trading fees + BTC/STX rewards.",
    lockupPeriod: "None",
    minimumDeposit: null,
    supportedAssets: ["sBTC", "STX"],
    defiLlamaProject: "bitflow",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "alex-sbtc-alex",
    name: "ALEX — sBTC-ALEX Pool",
    shortName: "ALEX LP",
    slug: "alex-sbtc-alex",
    description: "Provide liquidity on ALEX AMM and earn trading fees + ALEX rewards",
    category: "DEX/LP",
    icon: "🔬",
    websiteUrl: "https://alexlab.co",
    appUrl: "https://app.alexlab.co",
    apy: 22.4, apyBase: 4.0, apyReward: 18.4,
    apyRange: { min: 12, max: 35 },
    earnAsset: "sBTC + ALEX",
    tvlUsd: 12_000_000,
    tvl7dChange: 2.1, tvl30dChange: 5.5,
    riskScore: 6.2, healthScore: 7.2, opportunityScore: 7.5,
    ilRisk: "Medium", smartContractRisk: "Medium",
    audited: true, auditFirms: ["Clarity Alliance"],
    protocolAge: 30,
    strategy: "LP in sBTC-ALEX pair. ALEX token emission rewards dominate APY.",
    lockupPeriod: "None",
    minimumDeposit: null,
    supportedAssets: ["sBTC", "ALEX"],
    defiLlamaProject: "alex",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "velar-sbtc",
    name: "Velar — sBTC Pool",
    shortName: "Velar",
    slug: "velar-sbtc",
    description: "LP on Velar DEX and earn VELAR token rewards",
    category: "DEX/LP",
    icon: "💧",
    websiteUrl: "https://velar.co",
    appUrl: "https://app.velar.co",
    apy: 18.6, apyBase: 3.5, apyReward: 15.1,
    apyRange: { min: 10, max: 28 },
    earnAsset: "sBTC + VELAR",
    tvlUsd: 8_000_000,
    tvl7dChange: 4.8, tvl30dChange: 19.2,
    riskScore: 5.9, healthScore: 7.0, opportunityScore: 7.1,
    ilRisk: "Low", smartContractRisk: "Medium",
    audited: false, auditFirms: [],
    protocolAge: 10,
    strategy: "LP in sBTC pool. VELAR token farming rewards + trading fee share.",
    lockupPeriod: "None",
    minimumDeposit: null,
    supportedAssets: ["sBTC", "VELAR"],
    defiLlamaProject: "velar",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "alex-stx-farm",
    name: "ALEX — STX-ALEX Farm",
    shortName: "ALEX Farm",
    slug: "alex-stx-farm",
    description: "High-yield token farming with ALEX emissions",
    category: "DEX/LP",
    icon: "🔥",
    websiteUrl: "https://alexlab.co",
    appUrl: "https://app.alexlab.co",
    apy: 45.0, apyBase: 5.0, apyReward: 40.0,
    apyRange: { min: 20, max: 60 },
    earnAsset: "STX + ALEX",
    tvlUsd: 9_000_000,
    tvl7dChange: -1.2, tvl30dChange: 2.1,
    riskScore: 7.1, healthScore: 6.8, opportunityScore: 6.9,
    ilRisk: "High", smartContractRisk: "Medium",
    audited: true, auditFirms: ["Clarity Alliance"],
    protocolAge: 30,
    strategy: "LP in STX-ALEX. High APY driven by token emissions. IL risk from divergence.",
    lockupPeriod: "None (variable APY)",
    minimumDeposit: null,
    supportedAssets: ["STX", "ALEX"],
    defiLlamaProject: "alex",
    lastUpdated: new Date().toISOString(),
  },
  {
    id: "arkadiko-diko",
    name: "Arkadiko — DIKO Stake",
    shortName: "Arkadiko",
    slug: "arkadiko-diko",
    description: "Stake DIKO governance token to earn protocol yield",
    category: "Yield",
    icon: "🏺",
    websiteUrl: "https://arkadiko.finance",
    appUrl: "https://app.arkadiko.finance",
    apy: 11.2, apyBase: 11.2, apyReward: 0,
    apyRange: { min: 8, max: 15 },
    earnAsset: "DIKO + USDA",
    tvlUsd: 3_000_000,
    tvl7dChange: 0.5, tvl30dChange: -2.1,
    riskScore: 6.5, healthScore: 6.2, opportunityScore: 5.5,
    ilRisk: "None", smartContractRisk: "Medium",
    audited: true, auditFirms: ["Clarity Alliance"],
    protocolAge: 28,
    strategy: "Stake DIKO governance token. Earn DIKO + USDA stablecoin from protocol fees.",
    lockupPeriod: "None",
    minimumDeposit: null,
    supportedAssets: ["DIKO"],
    defiLlamaProject: "arkadiko",
    lastUpdated: new Date().toISOString(),
  },
];
